In [165]:
# Useful starting lines
%matplotlib inline
import numpy as np
import datetime
import matplotlib.pyplot as plt

from helpers import *
from implementations import *
from Data_Cleaning import *
from training_procedure import *

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [141]:
initial_w = np.array([[0.5], [1.0]])
np.linalg.norm(initial_w), np.dot(initial_w.T, initial_w)

(1.118033988749895, array([[1.25]]))

In [127]:
initial_w = np.array([[0.5], [1.0]])
y = np.array([[0.1], [0.3], [0.5]])
tx = np.array([[2.3, 3.2], [1.0, 0.1], [1.4, 2.3]])
MAX_ITERS = 2
GAMMA = 0.1

expected_w = np.array([[0.463156], [0.939874]])
y = (y > 0.2) * 1.0
w, loss = logistic_regression(y, tx, expected_w, 0, GAMMA)
w, loss

(array([[0.463156],
        [0.939874]]),
 1.5336935954900122)

In [128]:
initial_w = np.array([[0.5], [1.0]])
y = np.array([[0.1], [0.3], [0.5]])
tx = np.array([[2.3, 3.2], [1.0, 0.1], [1.4, 2.3]])
MAX_ITERS = 2
GAMMA = 0.1

y = (y > 0.2) * 1.0
w, loss = logistic_regression(y, tx, initial_w, MAX_ITERS, GAMMA)
w, loss

(array([[0.37856053],
        [0.80113119]]),
 1.3483578175129305)

In [167]:
from helpers import *

initial_w = np.array([[0.5], [1.0]])
y = np.array([[0.1], [0.3], [0.5]])
tx = np.array([[2.3, 3.2], [1.0, 0.1], [1.4, 2.3]])
MAX_ITERS = 2
GAMMA = 0.1

lambda_ = 1.0
y = (y > 0.2) * 1.0
expected_w = np.array([[0.409111], [0.843996]])
w, loss = reg_logistic_regression(
    y, tx, lambda_, expected_w, 0, GAMMA
)
w, loss

(array([[0.409111],
        [0.843996]]),
 1.4073273893870055)

In [163]:
w_ = np.array([[0.409111], [0.843996]])
lambda_ = 1.0
lambda_*np.dot(w_.T, w_)

array([[0.87970106]])

In [166]:
from helpers import *

initial_w = np.array([[0.5], [1.0]])
y = np.array([[0.1], [0.3], [0.5]])
tx = np.array([[2.3, 3.2], [1.0, 0.1], [1.4, 2.3]])
MAX_ITERS = 2
GAMMA = 0.1

lambda_ = 1.0
y = (y > 0.2) * 1.0
w, loss = reg_logistic_regression(
    y, tx, lambda_, initial_w, MAX_ITERS, GAMMA
)
w, loss

(array([[0.21606187],
        [0.46774656]]),
 0.9721649929512526)

In [5]:
y, tx, ids = load_csv_data("train.csv", sub_sample=False)

In [107]:
tx.shape

(250000, 30)

In [108]:
def replaceFirstFeature(tx, initial_gamma):
    correct = tx[tx[:,0]!=-999][:,1:]
    ncorrect = tx[tx[:,0]==-999][:, 1:]

    # delete missing value columns 
    correct = np.delete(correct, [3, 4, 5, 11, 22, 23, 24, 25, 26, 27], axis = 1)
    ncorrect = np.delete(ncorrect, [3, 4, 5, 11, 22, 23, 24, 25, 26, 27], axis = 1)

    # transform the categorical features into one-hot features
    correct = np.hstack((correct, 
    (correct[:, 17] == 0).astype(np.float64)[:, np.newaxis],
    (correct[:, 17] == 1).astype(np.float64)[:, np.newaxis],
    (correct[:, 17] == 2).astype(np.float64)[:, np.newaxis],
    (correct[:, 17] == 3).astype(np.float64)[:, np.newaxis]))
    correct = np.delete(correct, 17, axis = 1)

    ncorrect = np.hstack((ncorrect, 
    (ncorrect[:, 17] == 0).astype(np.float64)[:, np.newaxis],
    (ncorrect[:, 17] == 1).astype(np.float64)[:, np.newaxis],
    (ncorrect[:, 17] == 2).astype(np.float64)[:, np.newaxis],
    (ncorrect[:, 17] == 3).astype(np.float64)[:, np.newaxis]))
    ncorrect = np.delete(ncorrect, 17, axis = 1)

    # # standardization
    # correct = standardize(correct)
    # ncorrect = standardize(ncorrect)

    # standardization
    correct[:, :-4] = standardize(correct[:, :-4])
    ncorrect[:, :-4] = standardize(ncorrect[:, :-4])

    num_feat = correct.shape[1]
    # add cross quadratic terms
    for i in range(num_feat):
        new_features_xx = np.multiply(correct[:, i:num_feat], correct[:, 0:num_feat-i])
        new_features_xxN = np.multiply(ncorrect[:, i:num_feat], ncorrect[:, 0:num_feat-i])
        xx = np.hstack([correct, new_features_xx])
        xxN = np.hstack([ncorrect, new_features_xxN])

    # # standardization
    # xx = standardize(xx)
    # xxN = standardize(xxN)

    # add the bias term 
    bias_term_xx = np.ones([xx.shape[0], 1])
    bias_term_xxN = np.ones([xxN.shape[0], 1])
    xx = np.hstack([bias_term_xx, xx])
    xxN = np.hstack([bias_term_xxN, xxN])

    w_init = np.zeros(xx.shape[1])
    best_w, best_loss = train_first_feature(tx[:,0][tx[:,0] != -999], xx, w_init, initial_gamma, 30, 0)
    newFirst = xxN.dot(best_w)
    print(f"Best loss: {best_loss}")
    tx[:,0][tx[:,0]==-999] = newFirst
    # tx[tx[:,0]==-999][:,0] = newFirst

    return tx

In [109]:
initial_gamma = 0.001
tx = replaceFirstFeature(tx, initial_gamma)

  3%|▎         | 1/30 [00:01<00:40,  1.40s/it]

Linear Regression SGD(0/29): loss=152.04840802599094


  7%|▋         | 2/30 [00:02<00:40,  1.44s/it]

Linear Regression SGD(1/29): loss=155.35716178706807


 10%|█         | 3/30 [00:04<00:38,  1.42s/it]

Linear Regression SGD(2/29): loss=152.06113909566614


 13%|█▎        | 4/30 [00:05<00:36,  1.42s/it]

Linear Regression SGD(3/29): loss=152.55575146754333


 17%|█▋        | 5/30 [00:07<00:35,  1.41s/it]

Linear Regression SGD(4/29): loss=152.1018049475845


 20%|██        | 6/30 [00:08<00:34,  1.43s/it]

Linear Regression SGD(5/29): loss=152.5417177013852


 23%|██▎       | 7/30 [00:09<00:32,  1.42s/it]

Linear Regression SGD(6/29): loss=152.41955645138373


 27%|██▋       | 8/30 [00:11<00:31,  1.41s/it]

Linear Regression SGD(7/29): loss=151.1427764900052


 30%|███       | 9/30 [00:12<00:29,  1.43s/it]

Linear Regression SGD(8/29): loss=158.49861142420178


 33%|███▎      | 10/30 [00:14<00:28,  1.42s/it]

Linear Regression SGD(9/29): loss=151.85042975114598


 37%|███▋      | 11/30 [00:15<00:26,  1.42s/it]

Linear Regression SGD(10/29): loss=150.8914756114209


 40%|████      | 12/30 [00:17<00:29,  1.65s/it]

Linear Regression SGD(11/29): loss=151.23200058416703


 43%|████▎     | 13/30 [00:20<00:31,  1.86s/it]

Linear Regression SGD(12/29): loss=150.78096389374937


 47%|████▋     | 14/30 [00:22<00:31,  1.97s/it]

Linear Regression SGD(13/29): loss=151.29604415314606


 50%|█████     | 15/30 [00:24<00:28,  1.92s/it]

Linear Regression SGD(14/29): loss=150.81342118013671


 53%|█████▎    | 16/30 [00:25<00:25,  1.83s/it]

Linear Regression SGD(15/29): loss=150.76558970218267


 57%|█████▋    | 17/30 [00:27<00:23,  1.78s/it]

Linear Regression SGD(16/29): loss=150.8540625080253


 60%|██████    | 18/30 [00:29<00:21,  1.79s/it]

Linear Regression SGD(17/29): loss=150.7462003948694


 63%|██████▎   | 19/30 [00:31<00:19,  1.78s/it]

Linear Regression SGD(18/29): loss=150.75569805622376


 67%|██████▋   | 20/30 [00:32<00:17,  1.80s/it]

Linear Regression SGD(19/29): loss=150.728652432


 70%|███████   | 21/30 [00:34<00:16,  1.79s/it]

Linear Regression SGD(20/29): loss=150.74471570263623


 73%|███████▎  | 22/30 [00:36<00:14,  1.77s/it]

Linear Regression SGD(21/29): loss=150.72491920557107


 77%|███████▋  | 23/30 [00:38<00:12,  1.81s/it]

Linear Regression SGD(22/29): loss=150.7253991212167


 80%|████████  | 24/30 [00:40<00:11,  1.85s/it]

Linear Regression SGD(23/29): loss=150.72434583274227


 83%|████████▎ | 25/30 [00:41<00:09,  1.82s/it]

Linear Regression SGD(24/29): loss=150.72305253485152


 87%|████████▋ | 26/30 [00:43<00:07,  1.81s/it]

Linear Regression SGD(25/29): loss=150.72353401066874


 90%|█████████ | 27/30 [00:46<00:06,  2.02s/it]

Linear Regression SGD(26/29): loss=150.72295230391768


 93%|█████████▎| 28/30 [00:49<00:04,  2.27s/it]

Linear Regression SGD(27/29): loss=150.7222346456378


 97%|█████████▋| 29/30 [00:50<00:02,  2.15s/it]

Linear Regression SGD(28/29): loss=150.72206435078525


100%|██████████| 30/30 [00:52<00:00,  1.76s/it]

Linear Regression SGD(29/29): loss=150.72210971098428
Best loss: 150.72206435078525


In [15]:
tx[tx[:,0]==-999][:,0], tx.shape

(array([], dtype=float64), (250000, 30))

In [19]:
model_training = split_according_num_split_jet(y, tx, ids)

In [20]:
tx_0 = model_training['0']['data']
tx_1 = model_training['1']['data']
tx_2 = model_training['2']['data']
tx_0.shape[0] + tx_1.shape[0] + tx_2.shape[0] == tx.shape[0]

True

In [21]:
tx_mean_meaningful_0 = np.zeros([tx_0.shape[1],])
for i in range(tx_0.shape[1]):
    tx_mean_meaningful_0[i] = np.mean(tx_0[:, i][tx_0[:, i] != -999])
    tx_0[:, i][tx_0[:, i] == -999] = tx_mean_meaningful_0[i]

In [ ]:
tx_mean_meaningful_1 = np.zeros([tx_1.shape[1],])
for i in range(tx_1.shape[1]):
    tx_mean_meaningful_1[i] = np.mean(tx_1[:, i][tx_1[:, i] != -999])
    tx_1[:, i][tx_1[:, i] == -999] = tx_mean_meaningful_1[i]

In [ ]:
tx_mean_meaningful_2 = np.zeros([tx_2.shape[1],])
for i in range(tx_2.shape[1]):
    tx_mean_meaningful_2[i] = np.mean(tx_2[:, i][tx_2[:, i] != -999])
    tx_2[:, i][tx_2[:, i] == -999] = tx_mean_meaningful_2[i]